runtime: python38

instance_class: F4_1G

error_handlers:
  - error_code: timeout
    file: time_out.html

  - error_code: over_quota
    file: over_qota.html

handlers:
- url: /(.*\.(mp4|csv))$
  static_files: \1
  upload: static/.*\.(mp4|csv)$